// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2kp2Gvc_9QyfUYMcdlXPPWsv1doctnk',
    appId: '1:610003250069:web:45a04caceebbe1c498649c',
    messagingSenderId: '610003250069',
    projectId: 'ghb-benefits',
    authDomain: 'ghb-benefits.firebaseapp.com',
    storageBucket: 'ghb-benefits.appspot.com',
    measurementId: 'G-BWL9LQFS5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmwBZVvFVLh7xi9ReqXjTrM6tmizzYqs',
    appId: '1:610003250069:android:60cf0db32b6e94ba98649c',
    messagingSenderId: '610003250069',
    projectId: 'ghb-benefits',
    storageBucket: 'ghb-benefits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVeua5qnW1HVA709oVscDKEHcWGxDVKc',
    appId: '1:610003250069:ios:26221b897802464898649c',
    messagingSenderId: '610003250069',
    projectId: 'ghb-benefits',
    storageBucket: 'ghb-benefits.appspot.com',
    iosClientId: '610003250069-la9aehvh03sd4cb54dslq0hhc53s6knq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghbBanefitsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyVeua5qnW1HVA709oVscDKEHcWGxDVKc',
    appId: '1:610003250069:ios:26221b897802464898649c',
    messagingSenderId: '610003250069',
    projectId: 'ghb-benefits',
    storageBucket: 'ghb-benefits.appspot.com',
    iosClientId: '610003250069-la9aehvh03sd4cb54dslq0hhc53s6knq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghbBanefitsAdmin',
  );
}
